### ISSUE TITLE
Not working with Plausible 2.0?

### ISSUE THREAD

**Issue by fabsau** [riesinger/plausible-exporter#10]
Hi there,

First of all, I want to express my gratitude for creating this exporter. However, I've encountered an issue with it not working properly with Plausible 2.0. I haven't tested it with older versions of Plausible, so I can't confirm if it works with those.

To provide some context, I've included the metrics I'm currently observing:

```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 5.8317e-05
go_gc_duration_seconds{quantile="0.25"} 5.8317e-05
go_gc_duration_seconds{quantile="0.5"} 5.8317e-05
go_gc_duration_seconds{quantile="0.75"} 5.8317e-05
go_gc_duration_seconds{quantile="1"} 5.8317e-05
go_gc_duration_seconds_sum 5.8317e-05
go_gc_duration_seconds_count 1
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 11
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.7"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.00784e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 3.182768e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4550
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 28070
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 8.57756e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.00784e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 5.414912e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 2.449408e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 4747
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 3.52256e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.86432e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.69801719936946e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 32817
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 2400
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 54288
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 65088
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 691458
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 524288
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 524288
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.7742864e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 8
# HELP plausible_bounce_rate Bounce rate for a given site in %
# TYPE plausible_bounce_rate gauge
plausible_bounce_rate{site_id="fabio.sauna.re"} 0
# HELP plausible_pageviews Number of page views for a given site
# TYPE plausible_pageviews gauge
plausible_pageviews{site_id="fabio.sauna.re"} 0
# HELP plausible_visit_duration Average visit duration for a given site in seconds
# TYPE plausible_visit_duration gauge
plausible_visit_duration{site_id="fabio.sauna.re"} 0
# HELP plausible_visitors Number of visitors for a given site
# TYPE plausible_visitors gauge
**plausible_visitors{site_id="fabio.sauna.re"} 0 (This should NOT be 0)**
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.03
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 10
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.4344192e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.69801719848e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.38533376e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 0
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```

As you can see, the `plausible_visitors` metric is consistently showing 0, which I believe is incorrect. I have visited the webpage multiple times, and Plausible has updated its metrics accordingly. I have also waited for the exporter to refresh the data, but the `plausible_visitors` metric remains at 0.

I want to emphasize that the site key I'm using is correct because when I intentionally provide a wrong key, I receive a 401 error. Here are the relevant logs from the exporter:
```
2023-10-22T23:26:04.578869330Z 2023/10/22 23:26:04 Starting server, listening on 0.0.0.0:8080
2023-10-22T23:26:04.721358891Z 2023/10/22 23:26:04 Data for site fabio.sauna.re was refreshed from plausible
2023-10-22T23:26:04.751443848Z 2023/10/22 23:26:04 Refreshing data for site sauna.re failed: plausible: unexpected HTTP status code 401 received (was a test!)
```

Additionally, here is the relevant section from the Docker Compose configuration:

```
    plausibleexporter:
        image: ghcr.io/riesinger/plausible-exporter:latest
        container_name: plausibleexporter
        restart: unless-stopped
        hostname: plausibleexporter
        depends_on:
            - traefik
        environment:
            - PLAUSIBLE_HOST=https://data.sauna.re
            - PLAUSIBLE_SITE_IDS=fabio.sauna.re
            - PLAUSIBLE_TOKEN=redacted
        networks:
            - monitoring
        labels:
            - traefik.enable=true
            - traefik.http.routers.plausibleexporter.entrypoints=https
            - traefik.http.routers.plausibleexporter.rule=Host(`plausibleexporter.example.com`)
            - traefik.http.routers.plausibleexporter.tls.certresolver=ssl
            - traefik.http.routers.plausibleexporter.service=plausibleexporter
            - traefik.http.services.plausibleexporter.loadbalancer.server.port=8080
            - com.centurylinklabs.watchtower.enable=true
```

I would greatly appreciate any assistance in resolving this issue and getting the exporter to work correctly with Plausible 2.0.

Thank you once again for your efforts in creating this exporter.

Best regards,
fabsau
